default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 1
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc
        connection_ttl: 36000
        # max time a session will last for
        connection_ttl: 900
      # === Interrupt Handler - Receives INTERRUPT signal and executes stream cancellation ===
      InterruptHandler:
        module: logic/interrupt/interrupt_handler
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
      QwenOmni:
        enabled: true
        module: llm/qwen_omni/llm_handler_qwen_omni
        model_name: "qwen-omni-turbo-realtime"
        # api_key: "" # default=os.getenv("DASHSCOPE_API_KEY") API key can be set here or via env var
        voice: "Serena" #"Chelsie", "Serena", "Ethan", "Cherry"
        enable_video_input: true
        video_frame_interval_ms: 1000 # Send one image frame every 1000ms to prevent congestion; adjust as needed (no less than 500ms per Omni docs)
        enable_text_output: true
        input_audio_format: "PCM_16000HZ_MONO_16BIT"
        output_audio_format: "PCM_24000HZ_MONO_16BIT"
        enable_turn_detection: false # Server-side VAD mode is currently not supported; default is false, do not modify
        enable_input_transcription: false # In manual mode, Omni input ASR performance is poor; default disabled, use standard ASR results directly
        transcription_model: "gummy-realtime-v1"
      # Musetalk and LiteAvatar can be selected via config; LiteAvatar is used by default
      # AvatarMusetalk:
      #   module: avatar/musetalk/avatar_handler_musetalk
      #   fps: 20  # Video frame rate
      #   batch_size: 2  # Batch processing frame count, must be greater than 2
      #   avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/yongen.mp4"  # Initialization video path
      #   avatar_model_dir: "models/musetalk/avatar_model"  # Default avatar model directory
      #   force_create_avatar: false  # Whether to force regenerate digital human data
      #   debug: false  # Whether to enable debug mode
      LiteAvatar:
        module: avatar/liteavatar/avatar_handler_liteavatar
        avatar_name: 20250408/sample_data
        fps: 25
        debug: false
        enable_fast_mode: false
        use_gpu: true
